project:
  type: website
  output-dir: _site

website:
  title: "witt3rd.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/witt3rd
      - icon: twitter
        href: https://twitter.com/dt_public
      - icon: linkedin
        href: https://www.linkedin.com/in/thompsondonald/
format:
  html:
    theme: quartz
    css: styles.css
execute:
  freeze: auto
